with-expecter: false
packages:
    github.com/jfelipearaujo-org/ms-product-catalog/internal/environment:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/environment/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Environment)"
    github.com/jfelipearaujo-org/ms-product-catalog/internal/repository:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/repository/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Repository)"
    github.com/jfelipearaujo-org/ms-product-catalog/internal/provider:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/provider/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Provider)"
    github.com/jfelipearaujo-org/ms-product-catalog/internal/adapter/database:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/adapter/database/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Service)"
    github.com/jfelipearaujo-org/ms-product-catalog/internal/service/category/get_category:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/service/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Service)"
    github.com/jfelipearaujo-org/ms-product-catalog/internal/service/category/create_category:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/service/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Service)"