version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: product
      MONGO_INITDB_ROOT_PASSWORD: product
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
    networks:
      - api-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=0
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./scripts/localstack/:/etc/localstack/init/ready.d/

  mongo_express:
    depends_on:
      - mongo_db
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: product
      ME_CONFIG_MONGODB_ADMINPASSWORD: product
      ME_CONFIG_MONGODB_URL: mongodb://product:product@mongo_db:27017/
    networks:
      - api-network

volumes:
  mongo_volume:

networks:
  api-network:
    driver: bridge