version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: product
      MONGO_INITDB_ROOT_PASSWORD: product
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
    networks:
      - api-network

  api:
    depends_on:
      - mongo_db
    image: ms-product-catalog:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - API_PORT=8080
      - API_ENV_NAME=development
      - API_VERSION=v1
      - DB_NAME=product_db
      - DB_URL=mongodb://product:product@mongo_db:27017/
    networks:
      - api-network

  mongo_express:
    depends_on:
      - mongo_db
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: product
      ME_CONFIG_MONGODB_ADMINPASSWORD: product
      ME_CONFIG_MONGODB_URL: mongodb://product:product@mongo_db:27017/
    networks:
      - api-network

volumes:
  mongo_volume:

networks:
  api-network:
    driver: bridge