apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-product-catalog-hpa
  namespace: ns-products
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-product-catalog
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50