apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-product-catalog-ingress
  namespace: ns-products
  annotations:
    nginx.ingress.kubernetes.io/app-root: /products
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-product-catalog
                port:
                  number: 8080