name: linter

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2

      - name: Commit report
        run: |
          git config --global user.name 'testname'
          git config --global user.email 'testemail@users.noreply.github.com'

      - name: golangci-lint
        run: golangci-lint run
